spring.application.name=order
server.port=8081

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=orderdb
spring.cassandra.username=root
spring.cassandra.password=root
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.authenticator=PasswordAuthenticator

